theme: jekyll-theme-midnight
title: TechAyurveda will take you to the Modern Ayurveda
discription: It is created by Priyal Mehta in 2020. Our vision is to make Ayurveda smarter with Industry Evolution 4.0
