theme: jekyll-theme-midnight
title: TechAyurveda 
discription: It is created by Priyal Mehta in 2020. Our vision is to make Ayurveda smarter with Industry Evolution 4.0
email: engpriyalmehta@gmail.com
contact no.: 7744871972
